# Python list

In [32]:
#Listas

In [33]:
v = []
for i in range(9):
    v.append(i)
print(v)

[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [34]:
v = [1,2,3,4,5,6]
print(v)

[1, 2, 3, 4, 5, 6]


In [35]:
print(len(v))

6


In [36]:
w = [1,2,3,4,5,6,7,8,9,10]

In [37]:
print(len(w))

10


In [38]:
lista = []
for i in range(len(w)):
    lista.append(i)
print(lista)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [39]:
# Tuplas

In [153]:
w = 1,2,3,4,5,6
w[0]= 0
print(w)

TypeError: 'tuple' object does not support item assignment

In [41]:
print(len(w))

6


In [42]:
#Diccionarios

In [43]:
d = {'nombre': 'Daniel', 'Edad': 24, 'Origen': 'Querétaro'}

In [44]:
print(d)

{'nombre': 'Daniel', 'Edad': 24, 'Origen': 'Querétaro'}


In [45]:
d['Edad']

24

In [46]:
w[0]

1

In [47]:
lista[2]

2

In [156]:
a = range(2,6)
print(list(a))

[2, 3, 4, 5]


In [157]:
b = [2,4,6,8,10,12]

# Numpy

In [162]:
import numpy as np
!pip install tensorflow

  Using cached https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
  Using cached https://files.pythonhosted.org/packages/4e/35/11749bf99b2d4e3cceb4d55ca22590b0d7c2c62b9de38ac4a4a7f4687421/gast-0.2.2.tar.gz
  Using cached https://files.pythonhosted.org/packages/d1/4f/950dfae467b384fc96bc6469de25d832534f6b4441033c39f914efd13418/astor-0.8.0-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/c0/4e/fd492e91abdc2d2fcb70ef453064d980688762079397f779758e055f6575/Markdown-3.1.1-py2.py3-none-any.whl
  Created wheel for absl-py: filename=absl_py-0.8.1-cp37-none-any.whl size=121171 sha256=b8f4f3f6114ecd19fda4456419f8c260e316aa36cc2086ba6cb14a63d79d96ec
  Stored in directory: C:\Users\osiri\AppData\Local\pip\Cache\wheels\a7\15\a0\0a0561549ad11cdc1bc8fa1191a353efd30facf6bfb507aefc
  Created wheel for termcolor: filename=termcolor-1.1.0-cp37-none-any.whl size=4835 sha256=d3364cb4f393ff16b172e7f13895

In [52]:
d = [2,3,4,5,6,7]

In [158]:
M = [list(a),b,d]

In [159]:
M

[[2, 3, 4, 5], [2, 4, 6, 8, 10, 12], [2, 3, 4, 5, 6, 7]]

In [55]:
M = [list(a),b,d]

In [56]:
M

[[0, 1, 2, 3, 4, 5], [2, 4, 6, 8, 10, 12], [2, 3, 4, 5, 6, 7]]

In [160]:
c = list(c)

In [161]:
c

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

In [59]:
#List optimazed form
k = [str(i) for i in c]
k
#Nota: existen reducciones con if
#Por ejemplo: saludo = 'HOLA' if lang=='es' else 'HI'

['1.0', '1.0', '1.0', '1.0', '1.0', '1.0']

In [103]:
np.array([1,2,3,4,5], dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

### Data type	Description
-  bool_	Boolean (True or False) stored as a byte
-  int_	Default integer type (same as C long; normally either int64 or int32)
- intc	Identical to C int (normally int32 or int64)
- intp	Integer used for indexing (same as C ssize_t; normally either int32 or int64)
- int8	Byte (-128 to 127)
- int16	Integer (-32768 to 32767)
- int32	Integer (-2147483648 to 2147483647)
- int64	Integer (-9223372036854775808 to 9223372036854775807)
- uint8	Unsigned integer (0 to 255)
- uint16	Unsigned integer (0 to 65535)
- uint32	Unsigned integer (0 to 4294967295)
- uint64	Unsigned integer (0 to 18446744073709551615)
- float_	Shorthand for float64.
- float16	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
- float32	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
- float64	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
- complex_	Shorthand for complex128.
- complex64	Complex number, represented by two 32-bit floats
- complex128	Complex number, represented by two 64-bit floats

In [72]:
z0 = [True, 1.4, 4, "lista"]
z = [type(i) for i in z0]
z

[bool, float, int, str]

In [164]:
#Nested list
A = []
x = []
for j in range(4):
    x.append(j)
    A.append(x)
print(A)
print(A[1][3])

[[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]]
3


In [168]:
#Nested list optimized form
np.array([range(i,i+6) for i in [2, 4, 6]])

array([[ 2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10, 11]])

In [117]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [169]:
np.ones(9, dtype='int64')

array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [124]:
np.ones((2,3), dtype='float32')

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [125]:
np.full((5,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [170]:
# np.arange(inicio,fin,paso)
np.arange(0, 20, 0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [171]:
#np.linspace(inicio,fin,# de elementos)
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [173]:
np.random.random((3, 3))

array([[0.09077843, 0.2435854 , 0.56035124],
       [0.2800437 , 0.32746746, 0.14737566],
       [0.1225581 , 0.86566187, 0.76394766]])

In [130]:
#Valores aleatorios entre 0 y 1
np.random.random(3)

array([0.00277948, 0.764924  , 0.4406065 ])

In [175]:
# Crea un arreglo de n,n aleatorio de valores normalmente distribuidos
# con un promedio de 0 y desviación standar 1
np.random.normal(0, 1, (3, 3))

array([[ 0.65346118, -2.43904999,  0.57336206],
       [ 1.35738876, -1.02602476, -0.30197274],
       [-0.7389644 , -0.39283405,  0.03843767]])

In [ ]:
# Crea un arreglo de n,n aleatorio normalmente distribuido en un intervalo [0,1)
# de enteros

In [138]:
# Crea una matriz identidad de n,n 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [146]:
# Cree una matriz no inicializada de n enteros
# Los valores serán lo que sea que ya exista en esa ubicación de memoria
np.empty(5)

array([0.2, 0.4, 0.6, 0.8, 1. ])