# Pandas

In [9]:
import pandas as pd
pandas.__version__

'0.25.1'

In [ ]:
import numpy as np

## Series

In [13]:
#Genera un arreglo indexada de datos
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [14]:
#Obtener solo los valores
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [15]:
#Obtener solo los indices
data.index

RangeIndex(start=0, stop=4, step=1)

In [16]:
data[1]

0.5

In [17]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [80]:
#Asignar nuevos indices
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [20]:
data['b']

0.5

In [21]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [83]:
data[2]

0.75

In [26]:
#De diccionario de Python a Series de Pandas
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [84]:
population['California':'Florida']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

## DataFrame

In [32]:
#Los DataFrame son arreglos generalizados numpy
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [34]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [35]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [36]:
states.columns

Index(['population', 'area'], dtype='object')

In [37]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

### Construyendo objetos DataFrame

In [38]:
# Desde objetos Series
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [45]:
#Desde una lista de diccionarios
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
#data
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [40]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [41]:
#Desde diccionario de objetos a Series
pd.DataFrame({'population': population,
              'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [42]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.050409  0.905522
b  0.782333  0.304409
c  0.087941  0.109228

In [46]:
#Desde un arreglo Numpy estructurado
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [47]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

## Index

In [49]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [50]:
ind[1]

3

In [51]:
# Recorrido 2
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [52]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [54]:
# Una diferencia que existe entre objetos Index y arreglos Numpy es que son inmutables:

import numpy as np
n = np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [56]:
n[2] = 0

In [57]:
n

array([1., 1., 0., 1., 1.])

In [58]:
ind[1] = 0

TypeError: Index does not support mutable operations

### Index como set ordenado

In [60]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [61]:
indA & indB  # intersección

Int64Index([3, 5, 7], dtype='int64')

In [62]:
indA | indB  # unión

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [63]:
indA ^ indB  # diferencia simétrica

Int64Index([1, 2, 9, 11], dtype='int64')

### Data indexing y selección

In [64]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [65]:
data['b']

0.5

In [69]:
'a' in data

True

In [70]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [71]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [72]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [74]:
#Revisión de elementos por index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [75]:
#Revisión de elementos por enteros
data[0:2]

a    0.25
b    0.50
dtype: float64

In [76]:
# por filtro
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [77]:
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

In [85]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [86]:
data[1]

'a'

In [87]:
data[1:3]

3    b
5    c
dtype: object

### El DataFrame como un diccionario

In [88]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [89]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [90]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [91]:
data.area is data['area']

True

In [92]:
data.pop is data['pop']

False

In [93]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

### El Dataframe como arreglo de dos dimensiones

In [94]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [95]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [96]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [97]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [98]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [99]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [103]:
data.ix[:3, :'pop']

C:\Users\osiri\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [105]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [106]:
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [107]:
data['Florida':'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [108]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [109]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121